### ISSUE TITLE
Animation must not block node starting

### ISSUE THREAD

**Issue by darentuzi** [eigerco/lumina-front#20]
![lumina animation](https://github.com/eigerco/lumina-front/assets/6965770/e2c867d5-587a-4e9d-8245-19009319dd00)
Currently the node only starts after this animation is done, blocking the node starting and prolonging time to action.
Either the functions should be made async and started or the animation be made to run on top of the node UI with z-index and then hidden once its done.
The node must not run sequentially after the animation.

**Comment by aaadamgo** [comment]
This has been done.
